### ISSUE TITLE
NPE on method call with paranthensis expression at call site

### ISSUE THREAD

**Issue by steveash** [cheptsov/AdvancedExpressionFolding#18]
I'm getting an error trying to open a class `PlainTextSerializer` from the project `https://github.com/universal-automata/liblevenshtein-java`

The relevant portion of the stack trace is below.  When I try to catch this in the debugger (i.e. running the plguin sandbox and try to do this) -- i can't see to catch this.  The file wont open there either -- but it just spins without any errors logged to idea.log.  Very strange.

```java
java.lang.NullPointerException
	at com.intellij.advancedExpressionFolding.AdvancedExpressionFoldingBuilder.findChildExpressions(AdvancedExpressionFoldingBuilder.java:375)
	at com.intellij.advancedExpressionFolding.AdvancedExpressionFoldingBuilder.getExpression(AdvancedExpressionFoldingBuilder.java:356)
	at com.intellij.advancedExpressionFolding.AdvancedExpressionFoldingBuilder.getExpression(AdvancedExpressionFoldingBuilder.java:334)
	at com.intellij.advancedExpressionFolding.AdvancedExpressionFoldingBuilder.getMethodCallExpression(AdvancedExpressionFoldingBuilder.java:763)
	at com.intellij.advancedExpressionFolding.AdvancedExpressionFoldingBuilder.getExpression(AdvancedExpressionFoldingBuilder.java:280)
	at com.intellij.advancedExpressionFolding.AdvancedExpressionFoldingBuilder.buildFoldRegions(AdvancedExpressionFoldingBuilder.java:154)
	at com.intellij.advancedExpressionFolding.AdvancedExpressionFoldingBuilder.buildFoldRegions(AdvancedExpressionFoldingBuilder.java:178)
	at com.intellij.advancedExpressionFolding.AdvancedExpressionFoldingBuilder.buildFoldRegions(AdvancedExpressionFoldingBuilder.java:178)
	at com.intellij.advancedExpressionFolding.AdvancedExpressionFoldingBuilder.buildFoldRegions(AdvancedExpressionFoldingBuilder.java:178)
	at com.intellij.advancedExpressionFolding.AdvancedExpressionFoldingBuilder.buildFoldRegions(AdvancedExpressionFoldingBuilder.java:178)
	at com.intellij.advancedExpressionFolding.AdvancedExpressionFoldingBuilder.buildFoldRegions(AdvancedExpressionFoldingBuilder.java:178)
	at com.intellij.advancedExpressionFolding.AdvancedExpressionFoldingBuilder.buildFoldRegions(AdvancedExpressionFoldingBuilder.java:178)
	at com.intellij.advancedExpressionFolding.AdvancedExpressionFoldingBuilder.buildFoldRegions(AdvancedExpressionFoldingBuilder.java:178)
	at com.intellij.advancedExpressionFolding.AdvancedExpressionFoldingBuilder.buildFoldRegions(AdvancedExpressionFoldingBuilder.java:178)
```

**Comment by cheptsov** [comment]
Could you please re-check it with the latest version?

**Comment by cheptsov** [comment]
Will close it for now. Please re-open if you see this issue again in the new version.
