### ISSUE TITLE
Exception in Studio core -> RuntimeException: Exception while applying information to Editor

### ISSUE THREAD

**Issue by ciscorucinski** [cheptsov/AdvancedExpressionFolding#40]
This exception will occur with every single user interaction with the Editor

    Exception while applying information to Editor: file://C:/Users/Christopher/AndroidStudioProjects/AndroidStudioActivityTemplates/templates/basic activity/fragment/src/main/java/io/github/ciscorucinski/androidstudio/activitytemplate/basicactivityfragment/MainActivity.java(com.intellij.ide.highlighter.JavaFileType@5a13f3de)
    java.lang.RuntimeException: Exception while applying information to Editor: file://C:/Users/Christopher/AndroidStudioProjects/AndroidStudioActivityTemplates/templates/basic activity/fragment/src/main/java/io/github/ciscorucinski/androidstudio/activitytemplate/basicactivityfragment/MainActivity.java(com.intellij.ide.highlighter.JavaFileType@5a13f3de)
        at com.intellij.codeInsight.daemon.impl.PassExecutorService$3.run(PassExecutorService.java:521)
        at com.intellij.openapi.application.TransactionGuardImpl$6.run(TransactionGuardImpl.java:291)
        at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:326)
        at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:310)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
        at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:795)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:631)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:387)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
    Caused by: java.lang.IndexOutOfBoundsException: Wrong offset: -1. Should be in range: [0, 1639]
        at com.intellij.openapi.editor.impl.LineSet.findLineIndex(LineSet.java:141)
        at com.intellij.openapi.editor.impl.DocumentImpl.getLineNumber(DocumentImpl.java:919)
        at com.intellij.openapi.editor.impl.view.EditorCoordinateMapper.offsetToVisualLine(EditorCoordinateMapper.java:199)
        at com.intellij.openapi.editor.impl.view.EditorView.offsetToVisualLine(EditorView.java:174)
        at com.intellij.openapi.editor.impl.view.EditorSizeManager.doInvalidateRange(EditorSizeManager.java:307)
        at com.intellij.openapi.editor.impl.view.EditorSizeManager.invalidateRange(EditorSizeManager.java:300)
        at com.intellij.openapi.editor.impl.view.EditorView.invalidateRange(EditorView.java:308)
        at com.intellij.openapi.editor.impl.EditorImpl$1.attributesChanged(EditorImpl.java:417)
        at com.intellij.openapi.editor.impl.EditorImpl$1.afterAdded(EditorImpl.java:381)
        at com.intellij.openapi.editor.impl.MarkupModelImpl.fireAfterAdded(MarkupModelImpl.java:231)
        at com.intellij.openapi.editor.impl.MarkupModelImpl.addRangeHighlighter(MarkupModelImpl.java:136)
        at com.intellij.openapi.editor.impl.MarkupModelImpl.addRangeHighlighterAndChangeAttributes(MarkupModelImpl.java:122)
        at com.intellij.openapi.editor.impl.MarkupModelImpl.addRangeHighlighter(MarkupModelImpl.java:174)
        at com.intellij.advancedExpressionFolding.AdvancedExpressionFoldingHighlightingComponent.processRegion(AdvancedExpressionFoldingHighlightingComponent.java:114)
        at com.intellij.advancedExpressionFolding.AdvancedExpressionFoldingHighlightingComponent$2.onFoldRegionStateChange(AdvancedExpressionFoldingHighlightingComponent.java:80)
        at com.intellij.openapi.editor.impl.FoldingModelImpl.notifyListenersOnFoldRegionStateChange(FoldingModelImpl.java:584)
        at com.intellij.openapi.editor.impl.FoldingModelImpl.collapseFoldRegion(FoldingModelImpl.java:387)
        at com.intellij.openapi.editor.impl.FoldRegionImpl.doSetExpanded(FoldRegionImpl.java:90)
        at com.intellij.openapi.editor.impl.FoldRegionImpl.setExpanded(FoldRegionImpl.java:69)
        at com.intellij.codeInsight.folding.impl.UpdateFoldRegionsOperation.applyExpandStatus(UpdateFoldRegionsOperation.java:108)
        at com.intellij.codeInsight.folding.impl.UpdateFoldRegionsOperation.run(UpdateFoldRegionsOperation.java:95)
        at com.intellij.openapi.editor.impl.FoldingModelImpl.runBatchFoldingOperation(FoldingModelImpl.java:225)
        at com.intellij.openapi.editor.impl.FoldingModelImpl.runBatchFoldingOperationDoNotCollapseCaret(FoldingModelImpl.java:240)
        at com.intellij.codeInsight.folding.impl.FoldingUpdate.lambda$getUpdateResult$1(FoldingUpdate.java:120)
        at com.intellij.codeInsight.folding.impl.CodeFoldingManagerImpl.lambda$updateFoldRegionsAsync$2(CodeFoldingManagerImpl.java:323)
        at com.intellij.codeInsight.daemon.impl.CodeFoldingPass.doApplyInformationToEditor(CodeFoldingPass.java:59)
        at com.intellij.codeHighlighting.TextEditorHighlightingPass.applyInformationToEditor(TextEditorHighlightingPass.java:115)
        at com.intellij.codeInsight.daemon.impl.PassExecutorService$3.run(PassExecutorService.java:508)
        ... 20 more

Environment 
--------

    Android Studio 2.3
    Build #AI-162.3764568, built on February 24, 2017
    JRE: 1.8.0_112-release-b06 amd64
    JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

    ----

    Advanced Expression Folding Plugin version: 0.7.5

**Comment by ciscorucinski** [comment]
Issue occurs in 

- `0.7.5`
- `0.7.6`
- `0.7.7`

Notes
-----

It doesn't occur in every file, but one of my files will always throw this issue.

Code
-----

	package io.github.ciscorucinski.androidstudio.activitytemplate.basicactivityfragment;
	
	import android.os.Bundle;
	import android.support.design.widget.FloatingActionButton;
	import android.support.design.widget.Snackbar;
	import android.support.v7.app.AppCompatActivity;
	import android.support.v7.widget.Toolbar;
	import android.view.View;
	import android.view.Menu;
	import android.view.MenuItem;
	
	public class MainActivity extends AppCompatActivity {
	
		@Override
		protected void onCreate(Bundle savedInstanceState) {
	
			super.onCreate(savedInstanceState);
			setContentView(R.layout.activity_main);
			Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
			setSupportActionBar(toolbar);
	
			FloatingActionButton fab = (FloatingActionButton) findViewById(R.id.fab);
			fab.setOnClickListener(new View.OnClickListener() {
	
				@Override
				public void onClick(View view) {
	
					Snackbar.make(view, "Replace with your own action", Snackbar.LENGTH_LONG)
							.setAction("Action", null).show();
	
				}
			});
	
		}
	
		@Override
		public boolean onCreateOptionsMenu(Menu menu) {
			// Inflate the menu; this adds items to the action bar if it is present.
			getMenuInflater().inflate(R.menu.menu_main, menu);
			return true;
		}
	
		@Override
		public boolean onOptionsItemSelected(MenuItem item) {
			// Handle action bar item clicks here. The action bar will
			// automatically handle clicks on the Home/Up button, so long
			// as you specify a parent activity in AndroidManifest.xml.
			int id = item.getItemId();
	
			//noinspection SimplifiableIfStatement
			if (id == R.id.action_settings) {
				return true;
			}
	
			return super.onOptionsItemSelected(item);
		}
	}

**Comment by ultraon** [comment]
For me it's happened with file KeyStore.java, see details:
`Exception while applying information to Editor: file:///Users/my_user/Develop/android_sdk/sources/android-25/java/security/KeyStore.java(com.intellij.ide.highlighter.JavaFileType@625602fa)`

**Comment by cheptsov** [comment]
I found that this was a problem with IntelliJ IDEA 2016.2, which was actually fixed in IntelliJ IDEA 2016.2.5.

**Comment by ciscorucinski** [comment]
OK, so AS 2.3 uses at least 2016.2  ( I don't think it was updated to 2016.2.5)

But AS 2.4 Preview uses at least 2017.1

So either update the IDE to Preview or wait for a stable releases and update.
