### ISSUE TITLE
Error: java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by ultraon** [cheptsov/AdvancedExpressionFolding#55]
Hello, i've found issue related to this plugin, see stack trace:

> Exception while applying information to Editor: file:///Users/my_user/Develop/android_sdk/sources/android-25/java/security/KeyStore.java(com.intellij.ide.highlighter.JavaFileType@625602fa)
> java.lang.RuntimeException: Exception while applying information to Editor: file:///Users/my_user/Develop/android_sdk/sources/android-25/java/security/KeyStore.java(com.intellij.ide.highlighter.JavaFileType@625602fa)
> 	at com.intellij.codeInsight.daemon.impl.PassExecutorService$3.run(PassExecutorService.java:521)
> 	at com.intellij.openapi.application.TransactionGuardImpl$6.run(TransactionGuardImpl.java:291)
> 	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:326)
> 	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:310)
> 	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
> 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
> 	at java.awt.EventQueue.access$500(EventQueue.java:97)
> 	at java.awt.EventQueue$3.run(EventQueue.java:709)
> 	at java.awt.EventQueue$3.run(EventQueue.java:703)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
> 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
> 	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:795)
> 	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:631)
> 	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:387)
> 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
> 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
> 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
> 	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
> Caused by: java.lang.IndexOutOfBoundsException: Wrong offset: -1. Should be in range: [0, 68833]
> 	at com.intellij.openapi.editor.impl.LineSet.findLineIndex(LineSet.java:141)
> 	at com.intellij.openapi.editor.impl.DocumentImpl.getLineNumber(DocumentImpl.java:919)
> 	at com.intellij.openapi.editor.impl.view.EditorCoordinateMapper.offsetToVisualLine(EditorCoordinateMapper.java:199)
> 	at com.intellij.openapi.editor.impl.view.EditorView.offsetToVisualLine(EditorView.java:174)
> 	at com.intellij.openapi.editor.impl.view.EditorSizeManager.doInvalidateRange(EditorSizeManager.java:307)
> 	at com.intellij.openapi.editor.impl.view.EditorSizeManager.invalidateRange(EditorSizeManager.java:300)
> 	at com.intellij.openapi.editor.impl.view.EditorView.invalidateRange(EditorView.java:308)
> 	at com.intellij.openapi.editor.impl.EditorImpl$1.attributesChanged(EditorImpl.java:417)
> 	at com.intellij.openapi.editor.impl.EditorImpl$1.afterAdded(EditorImpl.java:381)
> 	at com.intellij.openapi.editor.impl.MarkupModelImpl.fireAfterAdded(MarkupModelImpl.java:231)
> 	at com.intellij.openapi.editor.impl.MarkupModelImpl.addRangeHighlighter(MarkupModelImpl.java:136)
> 	at com.intellij.openapi.editor.impl.MarkupModelImpl.addRangeHighlighterAndChangeAttributes(MarkupModelImpl.java:122)
> 	at com.intellij.openapi.editor.impl.MarkupModelImpl.addRangeHighlighter(MarkupModelImpl.java:174)
> 	at com.intellij.advancedExpressionFolding.AdvancedExpressionFoldingHighlightingComponent.processRegion(AdvancedExpressionFoldingHighlightingComponent.java:119)
> 	at com.intellij.advancedExpressionFolding.AdvancedExpressionFoldingHighlightingComponent$2.onFoldRegionStateChange(AdvancedExpressionFoldingHighlightingComponent.java:83)
> 	at com.intellij.openapi.editor.impl.FoldingModelImpl.notifyListenersOnFoldRegionStateChange(FoldingModelImpl.java:584)
> 	at com.intellij.openapi.editor.impl.FoldingModelImpl.collapseFoldRegion(FoldingModelImpl.java:387)
> 	at com.intellij.openapi.editor.impl.FoldRegionImpl.doSetExpanded(FoldRegionImpl.java:90)
> 	at com.intellij.openapi.editor.impl.FoldRegionImpl.setExpanded(FoldRegionImpl.java:69)
> 	at com.intellij.codeInsight.folding.impl.UpdateFoldRegionsOperation.applyExpandStatus(UpdateFoldRegionsOperation.java:108)
> 	at com.intellij.codeInsight.folding.impl.UpdateFoldRegionsOperation.run(UpdateFoldRegionsOperation.java:95)
> 	at com.intellij.openapi.editor.impl.FoldingModelImpl.runBatchFoldingOperation(FoldingModelImpl.java:225)
> 	at com.intellij.openapi.editor.impl.FoldingModelImpl.runBatchFoldingOperationDoNotCollapseCaret(FoldingModelImpl.java:240)
> 	at com.intellij.codeInsight.folding.impl.FoldingUpdate.lambda$getUpdateResult$1(FoldingUpdate.java:120)
> 	at com.intellij.codeInsight.folding.impl.CodeFoldingManagerImpl.lambda$updateFoldRegionsAsync$2(CodeFoldingManagerImpl.java:323)
> 	at com.intellij.codeInsight.daemon.impl.CodeFoldingPass.doApplyInformationToEditor(CodeFoldingPass.java:59)
> 	at com.intellij.codeHighlighting.TextEditorHighlightingPass.applyInformationToEditor(TextEditorHighlightingPass.java:115)
> 	at com.intellij.codeInsight.daemon.impl.PassExecutorService$3.run(PassExecutorService.java:508)
> 	... 20 more

**Comment by ultraon** [comment]
Sorry, it is duplicated the issue: https://github.com/cheptsov/AdvancedExpressionFolding/issues/40
